<?php

// created manually - QM 12.10.4 + QM 13.01

$qmrealtime_blocks = array(
	"RealTimeDO.RTRiassunto",
	"RealTimeDO.RTCallsBeingProc",    
	"RealTimeDO.RTAgentsLoggedIn",    
	"RealTimeDO.WallRiassunto",
	"RealTimeDO.WallCallsBeingProc",    
	"RealTimeDO.VisitorCallsProc",    
	"RealTimeDO.VisitorTodaysOk",    
	"RealTimeDO.VisitorTodaysKo",    
	"RealTimeDO.RtLiveQueues",    
	"RealTimeDO.RtLiveCalls",    
	"RealTimeDO.RtLiveAgents",    
	"RealTimeDO.RtLIveStatus",    
	"RealTimeDO.RtAgentsRaw", 
	"RealTimeDO.RtCallsRaw",
	"RealTimeDO.QueuesAndTagsView", 
	"RealTimeDO.QueuesAndTimesView", 
	"RealTimeDO.AgentAndOutcomeView", 	
);

?>
